Separate setting API_HOST and API_TOKEN
Arvados-DCO-1.1-Signed-off-by: Peter Amstutz <peter.amstutz@curii.com>

diff --git a/scripts/setup-env b/scripts/setup-env
--- a/scripts/setup-env
+++ b/scripts/setup-env
@@ -1,5 +1,5 @@
-test -s API_HOST || (echo "missing API_HOST, run the 'Configure Arvados' task"; exit 1)
-test -s API_TOKEN || (echo "missing API_TOKEN, run the 'Configure Arvados' task"; exit 1)
+test -s API_HOST || (echo "missing API_HOST, run the 'Set Arvados Host' task"; exit 1)
+test -s API_TOKEN || (echo "missing API_TOKEN, run the 'Set Arvados Token' task"; exit 1)
 export ARVADOS_API_HOST=$(cat API_HOST)
 export ARVADOS_API_TOKEN=$(cat API_TOKEN)
 if test -s $DIR/PROJECT_UUID ; then
